/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FanRouteImport } from './routes/fan'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FanTransportRouteImport } from './routes/fan.transport'
import { Route as FanTicketsRouteImport } from './routes/fan.tickets'
import { Route as FanTacticalRouteImport } from './routes/fan.tactical'
import { Route as AdminTransportRouteImport } from './routes/admin.transport'

const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FanTransportRoute = FanTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => FanRoute,
} as any)
const FanTicketsRoute = FanTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => FanRoute,
} as any)
const FanTacticalRoute = FanTacticalRouteImport.update({
  id: '/tactical',
  path: '/tactical',
  getParentRoute: () => FanRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/emergency': typeof EmergencyRoute
  '/fan': typeof FanRouteWithChildren
  '/login': typeof LoginRoute
  '/security': typeof SecurityRoute
  '/tournament': typeof TournamentRoute
  '/admin/transport': typeof AdminTransportRoute
  '/fan/tactical': typeof FanTacticalRoute
  '/fan/tickets': typeof FanTicketsRoute
  '/fan/transport': typeof FanTransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/emergency': typeof EmergencyRoute
  '/fan': typeof FanRouteWithChildren
  '/login': typeof LoginRoute
  '/security': typeof SecurityRoute
  '/tournament': typeof TournamentRoute
  '/admin/transport': typeof AdminTransportRoute
  '/fan/tactical': typeof FanTacticalRoute
  '/fan/tickets': typeof FanTicketsRoute
  '/fan/transport': typeof FanTransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/emergency': typeof EmergencyRoute
  '/fan': typeof FanRouteWithChildren
  '/login': typeof LoginRoute
  '/security': typeof SecurityRoute
  '/tournament': typeof TournamentRoute
  '/admin/transport': typeof AdminTransportRoute
  '/fan/tactical': typeof FanTacticalRoute
  '/fan/tickets': typeof FanTicketsRoute
  '/fan/transport': typeof FanTransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/emergency'
    | '/fan'
    | '/login'
    | '/security'
    | '/tournament'
    | '/admin/transport'
    | '/fan/tactical'
    | '/fan/tickets'
    | '/fan/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/emergency'
    | '/fan'
    | '/login'
    | '/security'
    | '/tournament'
    | '/admin/transport'
    | '/fan/tactical'
    | '/fan/tickets'
    | '/fan/transport'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/emergency'
    | '/fan'
    | '/login'
    | '/security'
    | '/tournament'
    | '/admin/transport'
    | '/fan/tactical'
    | '/fan/tickets'
    | '/fan/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  EmergencyRoute: typeof EmergencyRoute
  FanRoute: typeof FanRouteWithChildren
  LoginRoute: typeof LoginRoute
  SecurityRoute: typeof SecurityRoute
  TournamentRoute: typeof TournamentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan/transport': {
      id: '/fan/transport'
      path: '/transport'
      fullPath: '/fan/transport'
      preLoaderRoute: typeof FanTransportRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/tickets': {
      id: '/fan/tickets'
      path: '/tickets'
      fullPath: '/fan/tickets'
      preLoaderRoute: typeof FanTicketsRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/tactical': {
      id: '/fan/tactical'
      path: '/tactical'
      fullPath: '/fan/tactical'
      preLoaderRoute: typeof FanTacticalRouteImport
      parentRoute: typeof FanRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTransportRoute: typeof AdminTransportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTransportRoute: AdminTransportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FanRouteChildren {
  FanTacticalRoute: typeof FanTacticalRoute
  FanTicketsRoute: typeof FanTicketsRoute
  FanTransportRoute: typeof FanTransportRoute
}

const FanRouteChildren: FanRouteChildren = {
  FanTacticalRoute: FanTacticalRoute,
  FanTicketsRoute: FanTicketsRoute,
  FanTransportRoute: FanTransportRoute,
}

const FanRouteWithChildren = FanRoute._addFileChildren(FanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  EmergencyRoute: EmergencyRoute,
  FanRoute: FanRouteWithChildren,
  LoginRoute: LoginRoute,
  SecurityRoute: SecurityRoute,
  TournamentRoute: TournamentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
